
((lambda ()
   (define apt-elevator (Level))
   (define bkg-grad (apt-elevator 'make-entity 'bkg-grad))
   (define bkg-bldg1 (apt-elevator 'make-entity 'bkg-bldg1))
   (define camera-scroller (apt-elevator 'make-entity 'scroller))
   (define view-size (sge-camera-get-viewsize))
   (*player* 'set-position (cons -600.0 -600.0))
   (sge-camera-set-target camera-scroller)
   (sge-camera-set-springiness 35.0)
   (sge-entity-set-position camera-scroller (cons 0.0 450.0))
   (sge-camera-set-center (cons 0.0 200.0))
   (sge-entity-set-animation bkg-grad (anim-ref 'anim-sunsetgrad))
   (sge-entity-set-animation bkg-bldg1 (anim-ref 'anim-sunsetbldg1))
   (sge-entity-set-position bkg-bldg1 (cons (/ (car view-size) -2)
                                            (+ (cdr view-size) 220)))
   (sge-entity-set-zorder bkg-grad -4)
   (sge-entity-set-zorder bkg-bldg1 -1)
   (sge-entity-set-scale bkg-grad (cons
                                   (/ (car view-size) 300)
                                   (/ (cdr view-size) 300)))
   (sge-entity-add-attrib bkg-grad sge-attrib-position-absolute)
   (lvl-set! apt-elevator)))
